Chi-Square test

In [9]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

In [10]:
data = {
    'Satisfaction': ['Very Satisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'Very Unsatisfied'],
    'Smart Thermostat': [50, 80, 60, 30, 20],
    'Smart Light': [70, 100, 90, 50, 50],
    'Total': [120, 180, 150, 80, 70]
}


In [11]:
df = pd.DataFrame(data)

In [12]:
df

Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70

In [22]:
# Create a contingency table using the relevant columns
contingency_table = df[['Smart Thermostat', 'Smart Light']]
contingency_table = pd.crosstab(df['Smart Thermostat'], df['Smart Light'])
contingency_table



Smart Light       50   70   90   100
Smart Thermostat                    
20                  1    0    0    0
30                  1    0    0    0
50                  0    1    0    0
60                  0    0    1    0
80                  0    0    0    1

1. State the Hypotheses:

In [24]:
# State the Hypotheses
print("\nHypotheses:")
print("Null Hypothesis (H0): There is no association between the type of smart home device and customer satisfaction levels.")
print("Alternative Hypothesis (H1): There is an association between the type of smart home device and customer satisfaction levels.")


Hypotheses:
Null Hypothesis (H0): There is no association between the type of smart home device and customer satisfaction levels.
Alternative Hypothesis (H1): There is an association between the type of smart home device and customer satisfaction levels.


2.Compute the Chi-Square Statistic:

In [25]:
# Perform the Chi-Square test
chi2, p, dof, expected = chi2_contingency(contingency_table)

# Print the results
print(f"Chi-Square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)


Chi-Square statistic: 15.000000000000002
P-value: 0.24143645097027544
Degrees of freedom: 12
Expected frequencies:
[[0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]]


3. Determine the Critical Value:


In [32]:
# Interpret the results
alpha = 0.05  # Set the significance level

print("\nSignificance Level (alpha):", alpha)
print("Degrees of Freedom:", dof)

if p < alpha:
    print("There is a significant association between device type and customer satisfaction.")
else:
    print("There is no significant association between device type and customer satisfaction.")

# Calculate the critical value
critical_value = chi2.ppf(1 - alpha, dof)

print("\nCritical Value:", critical_value)


Significance Level (alpha): 0.05
Degrees of Freedom: 4
There is no significant association between device type and customer satisfaction.

Critical Value: 9.487729036781154


4. Make a Decision:

In [33]:
# Calculate the critical value
critical_value = chi2.ppf(1 - alpha, dof)

print("\nCritical Value:", critical_value)

# Make the decision based on the Chi-Square statistic and critical value
if chi2_statistic > critical_value:
    print("Reject the null hypothesis.")
    print("There is sufficient evidence to suggest an association between device type and customer satisfaction.")
else:
    print("Fail to reject the null hypothesis.")
    print("There is not sufficient evidence to suggest an association between device type and customer satisfaction.")


Critical Value: 9.487729036781154
Fail to reject the null hypothesis.
There is not sufficient evidence to suggest an association between device type and customer satisfaction.
